export const categories = {
  processing: {
    structure: [],
    environment: [],
    data: ['primitive', 'composite', 'conversion', 'string', 'array'],
    control: ['relational', 'iteration', 'conditionals', 'logical'],
    shape: ['', '2d', 'curves', '3d', 'attributes', 'vertex', 'loading'],
    input: ['mouse', 'keyboard', 'files', 'time'],
    output: ['text', 'image', 'files'],
    transform: [],
    lights: ['lights', 'camera', 'coordinates', 'material'],
    color: ['setting', 'creating'],
    image: ['', 'loading', 'textures', 'pixels'],
    rendering: ['', 'shaders'],
    typography: ['', 'loading', 'attributes', 'metrics'],
    math: ['', 'operators', 'bitwise', 'calculation', 'trigonometry', 'random'],
    constants: [],
  },
  serial: ['serial', 'event'],
  video: ['movie', 'capture', 'events'],
  net: ['client', 'server', 'events'],
  sound: [
    'configuration',
    'io',
    'sampling',
    'effects',
    'noise',
    'oscillators',
    'envelopes',
    'analysis',
  ],
  io: ['gpio', 'i2c', 'led', 'pwm', 'servo', 'spi'],
};
